[supabase]
url = "https://jlphsnydmrjjchaoqegy.supabase.co"
key = "sb_publishable_MPrbqdE5YWnsCC61WicSPw_7UnOxz13"

[admin]
password = "supersecretpassword"

[gemini]
api_key = "AQ.Ab8RN6IU54xKCrsmM4RndoYiB_3qdHvukMj7IWlZdPyNNv-2_A"
